### ISSUE TITLE
[BUG] Profile Fragment Crash Due to NullPointerException

### ISSUE THREAD

**Issue by kiranofans** [WikiEducationFoundation/apps-android-wikiedudashboard#127]
**Summary:** 
App crashed after trying to open Profile fragment

**Steps to reproduce:** 
1. Open the app using Android Studio emulator 
2. Tap Profile tab -> loading page content
3. App crashed

**System logs:**
```
2019-10-14 16:03:28.202 3078-3078/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 3078
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.wikiedufoundation.wikiedudashboard.ui.profile.data.ProfileDetails.getProfileImage()' on a null object reference
        at org.wikiedufoundation.wikiedudashboard.ui.profile.view.ProfileFragment.setProfileData(**ProfileFragment.kt:151**)
        at org.wikiedufoundation.wikiedudashboard.ui.coursedetail.recentactivity.ProfilePresenterImpl$requestProfileDetails$1.onSuccess(**ProfilePresenterImpl.kt:20**)
        at org.wikiedufoundation.wikiedudashboard.ui.profile.RetrofitProfileProvider$requestProfileDetails$1.onResponse(**RetrofitProfileProvider.kt:40**)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Device and Android version:** 
Android Studio emulator, Nexus 6P API 28
 
**Would you like to work on the issue?**
No

**Comment by kulloveth** [comment]
@kiranofans  thats after recent pull right?

**Comment by ujjwalagrawal17** [comment]
Thanks for opening the issue. We need to resolve the issue soon.

**Comment by kiranofans** [comment]
@kulloveth yes.

**Comment by victorvicari** [comment]
@ujjwalagrawal17 I'll take a look.
