### ISSUE TITLE
[BUG] App Crashed Randomly 

### ISSUE THREAD

**Issue by kiranofans** [WikiEducationFoundation/apps-android-wikiedudashboard#234]
**Summary:** 
App crashed on Course Details of Profile or other pages due to `IllegalStateException: recyclerCOurseList must not be null` and similar exceptions first time install the newest version

**Steps to reproduce:** 
1. Pulled the latest code, install the new version (debug mode) using Android 
2. launch the app right after the installation, go to user's Profile -> Course details -> app crashes

**System logs:**
```
 --------- beginning of crash
2019-11-06 14:08:01.495 10162-10162/org.wikiedufoundation.wikiedudashboard.release E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.wikiedufoundation.wikiedudashboard.release, PID: 10162
    java.lang.IllegalStateException: recyclerCourseList must not be null
        at org.wikiedufoundation.wikiedudashboard.ui.courselist.view.CourseListFragment.setData(CourseListFragment.kt:79)
        at org.wikiedufoundation.wikiedudashboard.ui.courselist.presenter.CourseListPresenterImpl$requestDashboard$1.onSuccess(CourseListPresenterImpl.kt:28)
        at org.wikiedufoundation.wikiedudashboard.ui.courselist.provider.RetrofitCourseListProvider$requestCourseList$1.onResponse(RetrofitCourseListProvider.kt:21)
        at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:71)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```

**Device and Android version:** 

Samsung Galaxy Tab A, Android 7.1

**Would you like to work on the issue?**
Yes

**Comment by kiranofans** [comment]
Looking into it
